name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"     # every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

# <--  add this block (or put it under jobs.generate if you prefer) -->
permissions:
  contents: write            # allow the built-in token to push commits

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=black&color_dots=#d6d6d6,#e0e0e0,#eaeaea,#f2f2f2,#f9f9f9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output          # branch name you want
          force_orphan: true              # creates branch automatically if absent
          commit_message: "Update snake animation [skip ci]"
